config/routes.rb
Rails.application.routes.draw do
  root 'pictures#index'
  resources :pictures, only: [:index, :create, :destroy]
  get '/favorite' => 'pictures#favorites', as: "favorites"

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :pictures, only: [:index]
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  # belongs_to :type
  # belongs_to :category
  # by_star_field :picture_date
    # base_uri ''

# access key: Wc_sw7h2IsJOA11q7w7ZXq4iF9LYa2d5YVZ9jtP9QH4
# secret key: PEOevnCJYav4bdQUEJMvCOktpVNNhEAasEHYkYe0At0
# redirect permisions: urn:ietf:wg:oauth:2.0:oob
  #
  # scope :select_type, ->( type ) { Picture.where( 'type = ?', type )}
  # scope :select_favorite, ->( favorite ) { Picture.where( 'favorite = ?', true )}

  # validates :concept, :value, :picture_date, presence: { message: ": por favor llene el campo en blanco" }
  # validate :date_cannot_be_in_the_future
  # validates :value, numericality: { greater_than_or_equal_to: 0 }, presence: { message: ": por favor llene el valor, mayor que 0" }

  # def date_cannot_be_in_the_future
  #   unless picture_date.nil?
  #     if picture_date.to_date > Date.today
  #       errors.add( :picture_date, 'No puede ser un gasto futuro' )
  #     end
  #   end
  # end

end

app/controllers/api/v1/expenses_controller.rb
class Api::V1::PicturesController < ApplicationController
  before_action :set_picture
  protect_from_forgery with: :null_session

  def index
    pictures = Picture.order( "picture_date DESC" )

    if params[ :category ].present?
      pictures = Picture.where( "category LIKE ?", "%#{ params[ :category ] }%" )
    end
    if params[:type].present?
      pictures = Picture.where( "type LIKE ?", "%#{ params[ :type ] }%")
    end

    categories = Category.all
    types = Type.all

    render json: pictures
  end

  def create
    picture = Picture.new( safe_params )
    if picture.save
      render json: picture, status: 201
    else
      render json: { errors: picture.errors }, status: 422
    end
  end

  def update
    picture = Picture.find( params[ :id ] )
    if picture.update( safe_params )
      render json: picture, status: 200
    else
      render json: {errors: picture.errors}, status: 422
    end
  end

  def destroy
    picture = Picture.find( params[ :id ] )
    picture.destroy
    head :no_content
  end

  private
  def safe_params
    params.require(:picture).permit(:type_id, :picture_date, :category_id, :concept, :value)
  end

  def set_picture
    @picture = Picture.find(params[:id])
  end
end

app/controllers/api/v1/pictures_controller.rb
class Api::V1::PicturesController < ApplicationController
  before_action :set_picture
  protect_from_forgery with: :null_session

  def index
    pictures = Picture.order( "picture_date DESC" )

    if params[ :category ].present?
      pictures = Picture.where( "category LIKE ?", "%#{ params[ :category ] }%" )
    end
    if params[:type].present?
      pictures = Picture.where( "type LIKE ?", "%#{ params[ :type ] }%")
    end

    categories = Category.all
    types = Type.all

    render json: pictures
  end

  def create
    picture = Picture.new( safe_params )
    if picture.save
      render json: picture, status: 201
    else
      render json: { errors: picture.errors }, status: 422
    end
  end

  def update
    picture = Picture.find( params[ :id ] )
    if picture.update( safe_params )
      render json: picture, status: 200
    else
      render json: {errors: picture.errors}, status: 422
    end
  end

  def destroy
    picture = Picture.find( params[ :id ] )
    picture.destroy
    head :no_content
  end

  private
  def safe_params
    params.require(:picture).permit(:type_id, :picture_date, :category_id, :concept, :value)
  end

  def set_picture
    @picture = Picture.find(params[:id])
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/pictures_controller.rb
# frozen_string_literal: true
class PicturesController < ApplicationController
  def index
    @pictures = Unsplash::Photo.all
    # @photo = Unsplash::Photo.all

    # type_id = params[ :type_id ] unless params[ :type_id ] == ''
    # category_id = params[ :category_id ] unless params[ :category_id ] == ''

    # if type_id.present?
    #   @pictures = Picture.by_month( @picture_date ).select_type( type_id.to_i ).order("picture_date DESC")
    # end
    # if category_id.present?
    #   @pictures = Picture.by_month( @picture_date ).select_category( category_id.to_i ).order("picture_date DESC")
    # end
    # if category_id.present? && type_id.present?
    #   @pictures = Picture.by_month( @picture_date ).select_category( category_id.to_i ).select_type( type_id.to_i ).order("picture_date DESC")
    # end

    respond_to do |format|
      format.js
      format.html { render 'index' }
    end

  end

  def create
    @picture = Picture.new(picture_params)
    if @picture.save
      puts "Picture succesfully saved"
    else
      puts "Couldn't save picture"
    end

    # respond_to do |format|
    #   format.js
    #   format.html
    # end

  end

  def destroy
    @picture = Picture.find(params[ :id ])
    @picture.destroy

    redirect_to pictures_path
  end

  def favorites
    @pictures = Picture.all
  end
end

  # def destroy
  #   picture = Picture.find(params[:id])
  #   picture.destroy
  # end

  # def show
  #   @picture = Picture.find(params[:id])
  # end

  # def edit
  #   @picture = Picture.find(params[:id])
  # end

  # def update
  #   @picture = Picture.find(params[:id])
  #   @picture.update(picture_params)
  #
  #   redirect_to pictures_path
  # end
  # def picture_params
  #   params.require( :picture ).permit( :value, :concept, :picture_date, :type_id,  :category_id )
  # end

  # def months_list
  #   (1..12).map do |m|
  #     m.months.ago
  #   end
  # end

  private
  def picture_params
    params.permit( :description, :url )
  end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/pictures_helper.rb
# frozen_string_literal: true

module PicturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Unsplash navigate | Emmanuel Jaramillo Muñoz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous"> -->
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Unsplash navigate | la <strong>app</strong></a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="<%= 'active' if @tab == :favorites %>"><%= link_to "Favoritas", favorites_path %></li>
            <li class="<%= 'active' if @tab == :pictures %>"><%= link_to "Fotos", pictures_path %></li>
          </ul>
        </div>
      </div>
    </nav>

    <% if flash[:notice] %>
      <div class="alert alert-info"><%= flash[:notice] %></div>
    <% end %>

    <% if flash[:alert] %>
      <div class="alert alert-danger"><%= flash[:alert] %></div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/pictures/_row.html.erb
<tr>
  <td class="picture_date" data-id='<%= picture.id %>'>
    <div class="day"><%= picture.picture_date.day %></div>
    <div class="month"><%= picture.picture_date.strftime("%b") %></div>
  </td>
  <td>
    <div>
      <span class="type"><%= picture.type.name  %></span>
    </div>
    <div>
      <span class="concept"><%= picture.concept %></span>
    </div>
  </td>
  <td class="category text-right"><%= picture.category.name %></td>
  <td class="text-right" style="width: 170px;">
    <div class="amount"><%= picture.value %></div>
    <div class="actions">
      <%= link_to "<span class='glyphicon glyphicon-edit'></span> edit".html_safe, edit_picture_path( picture.id ), remote: true %>
      <%= link_to "<span class='glyphicon glyphicon-trash'></span> delete".html_safe, picture_path( picture.id ),:data => { :confirm => "Estas seguro?", :method => 'delete', remote: true } %>
  </td>
</tr>

app/views/pictures/favorites.html.erb
<div class="container">
  <div class="row">
    <div class="total-box col-md-3">
      <span>Lista de fotos</span>
      <button type="button" class="btn btn-secondary"><%= link_to "Fotos", pictures_path , class: "text-white" %> </button>
    </div>
    <div class="total-box col-md-3">
      <span>Favoritas</span>
      <button type="button" class="btn btn-secondary"><%= link_to "Favoritas", favorites_path , class: "text-white" %> </button>
    </div>
  </div>
  <div class="row" style="margin-top: 40px;">
    <div class="box col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading"><h3>Lista de favoritas</h3></div>
        <div class="panel-body">
          <div id="pictures-chart"">

            <% @pictures.each do |picture| %>
            <tr>
              <td>
              <p class="">Nombre: <%= picture.description %> </p>
              </td>
            </tr>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pictures/index.html.erb
<div class="container">
  <div class="row">
    <div class="total-box col-md-3">
      <span>Lista de fotos</span>
      <button type="button" class="btn btn-secondary"><%= link_to "Fotos", pictures_path , class: "text-white" %> </button>
    </div>
    <div class="total-box col-md-3">
      <span>Favoritas</span>
      <button type="button" class="btn btn-secondary"><%= link_to "Favoritas", favorites_path , class: "text-white" %> </button>
    </div>
  </div>

  <div class="row" style="margin-top: 40px;">
    <div class="box col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading"><h3>Lista de fotos</h3></div>
        <div class="panel-body">
          <div id="pictures-chart">

          <% @pictures.each do |picture| %>
            <p>Nombre: <%= picture.description %> </p>
            <img src=<%= picture.links.self %> alt=<%= picture.description %>>
            <%= form_tag pictures_path, method: :create do %>
              <%= hidden_field_tag( :description, picture.description ) %>
              <%= hidden_field_tag( :url, picture.links.url) %>
              <%= hidden_field_tag( :favorite_id, picture.id) %>
              <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
              <%= submit_tag "Guardar", class: "btn btn-primary btn-md" %>
            <% end %>
          <% end %>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= yield %>

app/views/pictures/new.js.erb
$('<%= j render "new", title: "Agregar gasto" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();